model_path: "/home/yutongx/3DUNet/checkpoints/checkpoint_10/best_checkpoint.pytorch"
# model configuration
model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  final_sigmoid: true
  f_maps: 64
  num_levels: 4
  layer_order: bcr
  is_segmentation: true
  testing: true
# predictor configuration
predictor:
  name: 'StandardPredictor'
# data loaders configuration
loaders:
  batch_size: 1
  mirror_padding: [16, 32, 32]
  raw_internal_path: raw
  num_workers: 8
  output_dir: "predictions/checkpoint_10"
  test:
    file_paths:
      - "/home/yutongx/local_data/preprocessed_3d_128_copy/val/"
    slice_builder:
      name: SliceBuilder
      patch_shape: [128, 128, 128]
      stride_shape: [96, 96, 96]
    transformer:
        raw:
          - name: ToTensor
            expand_dims: true